import './globals.css';
import type { Metadata } from 'next';
import { Analytics } from '@vercel/analytics/react';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      id='test'
      lang='en'
    >
      <body className={inter.className}>
        <main className='flex min-h-screen flex-col items-center justify-between p-4 lg:p-24'>
          <div className='w-full max-w-5xl text-sm'>
            <div className='fixed left-0 flex h-full w-full flex-col items-center justify-start gap-4 overflow-y-auto bg-gradient-to-t from-white via-white dark:from-black dark:via-black lg:static lg:h-auto lg:w-auto lg:bg-none'>
              {children}
            </div>
          </div>
        </main>

        <Analytics />
      </body>
    </html>
  );
}
