name: CI - Test TypeScript

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Run TypeScript Compiler
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # https://github.com/actions/checkout
      - run: npm ci
      - run: npm run test:types
      - run: npm run test:types:cypress
