# https://docs.cypress.io/guides/continuous-integration/github-actions
# https://github.com/marketplace/actions/cypress-io
name: CI - Test Code::Cypress

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  # https://github.com/cypress-io/cypress/issues/27731#issuecomment-1884893217
  TS_NODE_COMPILER: 1

jobs:
  build:
    name: Run Cypress Test Script
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm run start
