name: CI - Test ESLint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Run ESlint Test Script
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # https://github.com/actions/checkout
      - run: npm ci
      - run: npm run test:eslint
